TyuteeProj1/urls.py
from django.contrib import admin
from django.urls import path,include
from display.urls import *

#from music.views import * 

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index),
    path("display/",include('display.urls'),name="display"),   
    path('music/', include('music.urls'))
]

display/urls.py

from django.contrib import admin
from django.urls import path

from .views import *




#from music.views import * 

urlpatterns = [
    
    path("",index),   #music 
    path("add/", add),
    
]

music/urls.py
from django.contrib import admin
from django.urls import path, re_path

app_name="music"


from music.views import * 


#from music.views import * 

urlpatterns = [
    path('', index,name="musichome"),
    path('homelist/',indexlist),


    #http://localhost:8000/music/search/1001
    #1001, 1002,1003,1004.............
    #path('search'/<int:albumid>, search)
    #RE 
    path('delete/',delete),
    re_path(r'^search/([0-9,A-Z,a-z]+)/$', search)
    #r'^(?P<album_id>[0-9]+)/$'
#?P<albumid>
]

display/models.py
from django.db import models


class Mymath:
    number1 : int
    number2 : int
    result  : int






music/models.py
from django.db import models

# Create your models here.

class Album(models.Model):
    album_id = models.IntegerField(primary_key=True)
    album_name = models.CharField(max_length=100)
    album_pic  = models.CharField(max_length=250)
    musdir = models.CharField(max_length=100)

    def __str__(self):
        return self.album_name

class Song(models.Model):
    sname = models.CharField(max_length=70)
    singer = models.CharField(max_length=150)
    album_id = models.ForeignKey(Album,on_delete=models.CASCADE)



# C --
# R --
# U ---
# D---

display/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *



# Create your views here.
def index(request):
    data={'name':'Athaulla','hobby':'volleyball'}
    return render(request,'display/indexresponse.html',{'data1':data})
    #return HttpResponse(html)


def add(request):

    if request.method == "POST":
        #client : add(without data) --- send the html  -- form n1 and n2....submit (http://localhost:8000/add)
        math1 = Mymath()

        math1.number1 = int(request.POST["n1"])
        math1.number2 = int(request.POST["n2"])
        math1.result = math1.n1 + math1.n2

        data = {"mathobj1":math1}
        return render(request,"display/djangoaddresponse.html",{"response":data})
    else:  #without any data...
        return render(request,"display/djangoadd.html")
    #txt1 = "<html><body><h1> For Input {} , {} sum result is {} </h1> </body> </html>".format(n1,n2,res)
    #txt2 = "</h1> </body> </html>"
    #html = txt1+txt2



music/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from .models import *

# Create your views here.

def index(request):
    qs = Album.objects.all()
    print("Inside Views Display all Method")
    return render(request, 'music/index.html',{'qs':qs})  

    #return render(request, 'studapp/studresults.html',context={"qs":qs})
    
def indexlist(request):
    qs = Album.objects.all()
    print("Inside Views Display all Method")
    return render(request, 'music/indexlist.html',{'qs':qs})  

def search(request,albumid):
    
    try:
        qs = Song.objects.filter(album_id=albumid)  # dont use filter method....
    except Song.DoesNotExist:
        
	    raise Http404("Album doesnot Exist")
        #return render(request,'music/index.html', {'album':album})
    else:
        return render(request, 'music/detaillist.html',{'qs':qs})  


def delete(request):
    aid = int(request.POST['albumid'])
    arec = Album.objects.get(album_id=aid)

    arec.delete()
    print("Record deleted")
    



templates/display/djangoadd.html
<html>
<body>

<form action="http://localhost:8000/add/" method="POST">
{% csrf_token %}

<input type=text name="n1" placeholder="Enter Number">
<input type=text name="n2" placeholder="Enter Number">
<input type="submit"></input>
</form>


</body>
</html>

templates/display/djangoaddresponse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Response</title>
</head>
<body>
<h1> For Input {{response.mathobj1.number1}}, {{response.mathobj1.number2}} sum result is {{response.mathobj1.result}} </h1>
</body>
</html>

templates/display/gitindex.html
<html>
    <boby>
        <h1> this file will be moved </h1>
    </boby>
</html>

templates/display/indexresponse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Initial Request Response</title>
</head>
<body>
<h1> Welcome {{data1.name}} to Django Basic Website and ur hobby is {{data1.hobby}}</h1>
</body>
</html>




templates/gitindex2.html
<html>

<body>
    <h3> this is shld be part of index2</h3>
</body>
</html>

templates/music/actions.html
<html>

<body>

    
   <form action="##">
       <input type=text name='albumid' placeholder="Enter album id to delete">
       <input type=submit> 

   </form>

</body>
</html>

templates/music/detaillist.html
<html>
<body>
   
    <table border=2>

      {% if qs %}  
      <h1> These are records from Song Table - music app </h1>

       <tr>
       <th> Song Name </th>
       <th> Singer</th>
      
       </tr>
     {% for songrec in qs %}
       <tr>
         <td> {{songrec.sname}} </td>
         <td> {{songrec.singer}} </<td>
         
       </tr>

     {% endfor %}
   </table>
   {% else %}
   <h1> No Songs to display which matched entered criteria </h1>
   {% endif %}
</body>
</html> 

templates/music/index.html
<html>

<body>
    <h1> These are records from Album Table - music app </h1>

    <table border=2>

         {% if qs %}  
        
          <tr>
          <th> Album ID</th>
          <th> Album  Name </th>
          <th> Album PIC URL </th>
          <th> Album Music Dir </th>
         
          </tr>
        {% for albumrec in qs %}
          <tr>
            <td> {{albumrec.album_id}} </td>
            <td> {{albumrec.album_name}} </<td>
            <td> {{albumrec.album_pic}} </td>
            <td> {{albumrec.musdir}} </td>
           
          </tr>

        {% endfor %}
      </table>
      {% else %}
      <h1> No Album records to display which matched entered criteria </h1>
      {% endif %}
</body>
</html> 

templates/music/indexlist.html
<html>
<body>
    <h1> These are records from Album Table - music app </h1>

        {% if qs %}  
        
        <ol>
          {% for albumrec in qs %}

          <!--<a href="http://localhost:8000/music/search/{{albumrec.album_id}}"><li> {{albumrec.album_name}} </li> </a> -->
          

          <a href="{% url 'music:musichome' %}search/{{albumrec.album_id}}"><li> {{albumrec.album_name}} </li> </a> 
          {% endfor %}
      </ol>

      
      {% else %}
      <h1> No Album records to display which matched entered criteria </h1>
      
      {% endif %}
</body>
</html> 